on:
  release:
    types: [created]

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Publish
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY: ${{ secrets.S_SIGNING_KEY }}
          SIGNING_PW: ${{ secrets.S_SIGNING_PASSWORD }}
        run: ./gradlew clean publishToSonatype closeAndReleaseSonatypeStagingRepository
